# Generated by Django 5.2.15 on 2026-07-06 05:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='大会名')),
            ],
            options={
                'verbose_name': '大会',
                'verbose_name_plural': '大会',
                'db_table': 'competitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='国名')),
            ],
            options={
                'verbose_name': '対戦国',
                'verbose_name_plural': '対戦国',
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(verbose_name='試合日')),
                ('score_japan', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='日本の得点')),
                ('score_opponent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='相手の得点')),
                ('venue', models.CharField(max_length=200, verbose_name='会場')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='history.competition', verbose_name='大会')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='history.country', verbose_name='対戦国')),
            ],
            options={
                'verbose_name': '試合',
                'verbose_name_plural': '試合',
                'db_table': 'matches',
                'ordering': ['-match_date'],
            },
        ),
    ]
