# Generated by Django 5.2.15 on 2026-07-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goal_scorers',
            field=models.TextField(blank=True, default='', verbose_name='得点者'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_cards',
            field=models.TextField(blank=True, default='', verbose_name='退場者'),
        ),
        migrations.AddField(
            model_name='match',
            name='yellow_cards',
            field=models.TextField(blank=True, default='', verbose_name='警告者'),
        ),
    ]
