# Generated by Django 5.2.15 on 2026-07-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_match_goal_scorers_match_red_cards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='goal_scorers',
        ),
        migrations.AddField(
            model_name='match',
            name='away_goal_scorers',
            field=models.TextField(blank=True, default='', verbose_name='得点者'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_goal_scorers',
            field=models.TextField(blank=True, default='', verbose_name='得点者'),
        ),
    ]
